### ISSUE TITLE
gulp-uncss causes gulp_jspm to break in vinyl stream

### ISSUE THREAD

**Issue by selfagency** [gulpjs/vinyl#118]
for some reason, once i include gulp-uncss in my gulpfile, i'm no longer able to run my jspm build task. if i comment out the include of gulp-uncss, it works. and gulp-uncss works fine when i run my css build task with both packages included. but gulp_jspm breaks.

```
gulp.task('scripts', function() {
  gulp.src('src/scripts/**/*.js')
    .pipe(plumber({
      errorHandler: function(error) {
        console.log(error.message);
        this.emit('end');
      }
    }))
    .pipe(gulp.dest('public/scripts/'));
  gulp.src('public/scripts/main.js')
    .pipe(gulp_jspm({
      fileName: 'build',
      inject: true
    }))
    .pipe(gulp.dest('public/'))
    .pipe(browserSync.reload({
      stream: true
    }));
});
[01:37:09] Using gulpfile ~/Dev/nylon/nylon-microsites/gmc/gulpfile.js
[01:37:09] Starting 'scripts'...
[01:37:09] Finished 'scripts' after 13 ms

events.js:154
      throw er; // Unhandled 'error' event
      ^
Error: File.contents can only be a Buffer, a Stream, or null.
    at File.Object.defineProperty.set (/Users/daniel/Dev/nylon/nylon-microsites/gmc/node_modules/gulp-jspm/node_modules/vinyl/index.js:171:13)
    at new File (/Users/daniel/Dev/nylon/nylon-microsites/gmc/node_modules/gulp-jspm/node_modules/vinyl/index.js:34:17)
    at /Users/daniel/Dev/nylon/nylon-microsites/gmc/node_modules/gulp-jspm/index.js:183:13
From previous event:
    at do_bundle (/Users/daniel/Dev/nylon/nylon-microsites/gmc/node_modules/gulp-jspm/index.js:181:6)
    at DestroyableTransform._transform (/Users/daniel/Dev/nylon/nylon-microsites/gmc/node_modules/gulp-jspm/index.js:41:9)
    at DestroyableTransform.Transform._read (/Users/daniel/Dev/nylon/nylon-microsites/gmc/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:159:10)
    at DestroyableTransform.Transform._write (/Users/daniel/Dev/nylon/nylon-microsites/gmc/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:147:83)
    at doWrite (/Users/daniel/Dev/nylon/nylon-microsites/gmc/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:313:64)
    at writeOrBuffer (/Users/daniel/Dev/nylon/nylon-microsites/gmc/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:302:5)
    at DestroyableTransform.Writable.write (/Users/daniel/Dev/nylon/nylon-microsites/gmc/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:241:11)
    at write (/Users/daniel/Dev/nylon/nylon-microsites/gmc/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/Users/daniel/Dev/nylon/nylon-microsites/gmc/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (/Users/daniel/Dev/nylon/nylon-microsites/gmc/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:664:5)
    at emitNone (events.js:80:13)
    at DestroyableTransform.emit (events.js:179:7)
    at emitReadable_ (/Users/daniel/Dev/nylon/nylon-microsites/gmc/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:448:10)
    at emitReadable (/Users/daniel/Dev/nylon/nylon-microsites/gmc/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:444:5)
    at readableAddChunk (/Users/daniel/Dev/nylon/nylon-microsites/gmc/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:187:9)
    at DestroyableTransform.Readable.push (/Users/daniel/Dev/nylon/nylon-microsites/gmc/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:149:10)
    at DestroyableTransform.Transform.push (/Users/daniel/Dev/nylon/nylon-microsites/gmc/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_transform.js:145:32)
    at afterTransform (/Users/daniel/Dev/nylon/nylon-microsites/gmc/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_transform.js:101:12)
    at TransformState.afterTransform (/Users/daniel/Dev/nylon/nylon-microsites/gmc/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_transform.js:79:12)
    at DestroyableTransform.noop [as _transform] (/Users/daniel/Dev/nylon/nylon-microsites/gmc/node_modules/vinyl-fs/node_modules/through2/through2.js:26:3)
    at DestroyableTransform.Transform._read (/Users/daniel/Dev/nylon/nylon-microsites/gmc/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/Users/daniel/Dev/nylon/nylon-microsites/gmc/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/Users/daniel/Dev/nylon/nylon-microsites/gmc/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/Users/daniel/Dev/nylon/nylon-microsites/gmc/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at DestroyableTransform.Writable.write (/Users/daniel/Dev/nylon/nylon-microsites/gmc/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_writable.js:194:11)
```

**Comment by phated** [comment]
This isn't a gulp issue.  You've already stated it's a problem with your plugins so open your issues on those projects.
